import pytest

from printprep import PrintPrepError
from printprep.slicer import parse_material_profile

ORCA_JSON = """{
  "name": "My PLA",
  "filament_type": ["PLA"],
  "nozzle_temperature": ["215"],
  "hot_plate_temp": ["60"],
  "filament_retraction_length": ["0.6"],
  "filament_retraction_speed": ["35"],
  "filament_max_volumetric_speed": ["11"]
}"""

PRUSA_INI = """# generated by PrusaSlicer
[filament:My PETG]
filament_type = PETG
temperature = 240
bed_temperature = 85
filament_retract_length = 1.5
filament_retract_speed = 30
filament_max_volumetric_speed = 8
"""

CURA_XML = """<?xml version="1.0"?>
<fdmmaterial xmlns="http://www.ultimaker.com/material">
  <metadata><name><material>Generic ABS</material></name></metadata>
  <settings>
    <setting key="print temperature">250</setting>
    <setting key="heated bed temperature">100</setting>
    <setting key="retraction amount">1.0</setting>
    <setting key="retraction speed">45</setting>
  </settings>
</fdmmaterial>"""


def test_import_orca_json():
    p = parse_material_profile(ORCA_JSON, "my_pla.json")
    assert p.nozzle_temp_c == 215
    assert p.bed_temp_c == 60
    assert p.retraction_mm == 0.6
    assert p.retraction_speed_mms == 35
    assert p.max_volumetric_speed_mm3s == 11.0


def test_import_prusa_ini():
    p = parse_material_profile(PRUSA_INI, "my_petg.ini")
    assert p.nozzle_temp_c == 240
    assert p.bed_temp_c == 85
    assert p.retraction_mm == 1.5
    assert p.max_volumetric_speed_mm3s == 8.0


def test_import_cura_xml():
    p = parse_material_profile(CURA_XML, "abs.fdm_material")
    assert p.nozzle_temp_c == 250
    assert p.bed_temp_c == 100
    assert p.retraction_mm == 1.0
    assert p.retraction_speed_mms == 45
    # No volumetric flow in Cura XML -> conservative fallback.
    assert p.max_volumetric_speed_mm3s == 8.0


def test_import_missing_nozzle_raises():
    with pytest.raises(PrintPrepError):
        parse_material_profile('{"name": "broken"}', "broken.json")
